//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyPrint2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Equipment = new HashSet<Equipment>();
            this.Orders = new HashSet<Orders>();
            this.Service_Requests = new HashSet<Service_Requests>();
        }
    
        public int ID_Client { get; set; }
        public string Organization_Name { get; set; }
        public string Contact_Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Service_Requests> Service_Requests { get; set; }
    }
}
