//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyPrint2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Order_Items = new HashSet<Order_Items>();
            this.Service_Requests = new HashSet<Service_Requests>();
        }
    
        public int ID_Equipment { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Serial_Number { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public string Condition { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Order_Items> Order_Items { get; set; }
        public virtual ICollection<Service_Requests> Service_Requests { get; set; }
    }
}
