//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyPrint2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolyPrintEntities : DbContext
    {
        public PolyPrintEntities()
            : base("name=PolyPrintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<Order_Items> Order_Items { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Parts> Parts { get; set; }
        public DbSet<Service_Requests> Service_Requests { get; set; }
        public DbSet<Used_Parts> Used_Parts { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<Works> Works { get; set; }
    }
}
