//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyPrint2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public int ID_Order { get; set; }
        public int ID_Client { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Status { get; set; }
        public decimal Total { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Order_Items> Order_Items { get; set; }
    }
}
