//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyPrint2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public int ID_Item { get; set; }
        public int ID_Order { get; set; }
        public int ID_Equipment { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
