//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyPrint2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts
    {
        public Parts()
        {
            this.Used_Parts = new HashSet<Used_Parts>();
        }
    
        public int ID_Part { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<Used_Parts> Used_Parts { get; set; }
    }
}
