//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyPrint2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Requests
    {
        public Service_Requests()
        {
            this.Works = new HashSet<Works>();
        }
    
        public int ID_Request { get; set; }
        public int ID_Client { get; set; }
        public Nullable<int> ID_Equipment { get; set; }
        public System.DateTime Created_Date { get; set; }
        public string Problem_Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> ID_Master { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Works> Works { get; set; }
    }
}
