//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyPrint2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Works
    {
        public Works()
        {
            this.Used_Parts = new HashSet<Used_Parts>();
        }
    
        public int ID_Work { get; set; }
        public int ID_Request { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime Work_Date { get; set; }
    
        public virtual Service_Requests Service_Requests { get; set; }
        public virtual ICollection<Used_Parts> Used_Parts { get; set; }
    }
}
